version: "3.8"
services:
  # Mysql database container
  db:
    image: mysql
    container_name: env_dev_mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - env_dev

  # phpmyadmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: env_dev_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - env_dev

  #Service Mails
  maildev:
    image: maildev/maildev
    container_name: env_dev_maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always
    networks:
      - env_dev

  # Symfony apache project container
  www:
    build: php
    container_name: env_dev_www
    ports:
      - "8082:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - env_dev

networks:
  env_dev:


volumes:
  db-data:
